@host = http://127.0.0.1
@port = 8000



### 1. Crear una reseña (Como Usuario)
# Prueba esto con un usuario que SEPAS que tiene una reserva pasada
POST {{host}}:{{port}}/resenas/
Content-Type: application/json
Authorization: Bearer {{token}}

{
    "comentario": "La comida estuvo increíble, especialmente el solomillo. El servicio fue un poco lento pero valió la pena.",
    "puntuacion": 5,
    "fecha": "2026-02-11"
}

### 2. Intentar crear reseña sin reserva (Debería dar 403)
POST {{host}}:{{port}}/resenas/
Content-Type: application/json
Authorization: Bearer {{token}}

{
    "comentario": "Intento de reseña fraudulenta",
    "puntuacion": 1,
    "fecha": "2026-02-11"
}

### 3. Ver todas las reseñas (Como Admin)
GET {{host}}:{{port}}/resenas/
Authorization: Bearer {{token}}